grails-app/domain/com/springsecurity/User.groovy
package com.springsecurity

class User {

	transient springSecurityService

	String firstname
	String lastname
	String username
	String password
	Date dateCreated
	Date lastUpdated
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired

	static transients = ['springSecurityService']

	static constraints = {
		username blank: false, unique: true
		password blank: false
	}

	static mapping = {
		password column: '`password`'

	}

	Set<Role> getAuthorities() {
		UserRole.findAllByUser(this).collect { it.role }
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
	}
}

grails-app/controllers/com/springsecurity/LoginController.groovy
package com.springsecurity

import co.SignUpCO
import grails.converters.JSON
import grails.plugin.springsecurity.SpringSecurityUtils

import javax.servlet.http.HttpServletResponse

import org.springframework.security.access.annotation.Secured
import org.springframework.security.authentication.AccountExpiredException
import org.springframework.security.authentication.CredentialsExpiredException
import org.springframework.security.authentication.DisabledException
import org.springframework.security.authentication.LockedException
import org.springframework.security.core.context.SecurityContextHolder as SCH
import org.springframework.security.web.WebAttributes

@Secured('permitAll')
class LoginController {

    /**
     * Dependency injection for the authenticationTrustResolver.
     */
    def authenticationTrustResolver

    /**
     * Dependency injection for the springSecurityService.
     */
    def springSecurityService
    def loginService
    /**
     * Default action; redirects to 'defaultTargetUrl' if logged in, /login/auth otherwise.
     */
    def index() {

        if (springSecurityService.isLoggedIn()) {
            println SpringSecurityUtils.securityConfig.successHandler.defaultTargetUrl
            redirect controller: "mixPanel", action: 'dashboard'
            // redirect uri: SpringSecurityUtils.securityConfig.successHandler.defaultTargetUrl
        } else {
            redirect action: 'auth', params: params
        }
    }


    def saveSignUpData(SignUpCO signUpCO) {

        if (signUpCO.validate()) {

            loginService.signUpSave(signUpCO)
            redirect(controller: "login", action: "auth")
        } else {
            flash.error = signUpCO.errors
            redirect(action: 'auth', model: [signUpBean: signUpCO])
        }
    }


    def auth() {
        def config = SpringSecurityUtils.securityConfig
        if (springSecurityService.isLoggedIn()) {
            redirect(controller: "login", action: "dashboard")

            // redirect uri: config.successHandler.defaultTargetUrl
            return
        }
        //String view = 'auth'
        String view = 'home'
        String postUrl = "${request.contextPath}${config.apf.filterProcessesUrl}"
        render view: view, model: [postUrl            : postUrl,
                                   rememberMeParameter: config.rememberMe.parameter]
    }

    /**
     * The redirect action for Ajax requests.
     */
    def authAjax() {
        response.setHeader 'Location', SpringSecurityUtils.securityConfig.auth.ajaxLoginFormUrl
        response.sendError HttpServletResponse.SC_UNAUTHORIZED
    }

    /**
     * Show denied page.
     */
    def denied() {
        if (springSecurityService.isLoggedIn() &&
                authenticationTrustResolver.isRememberMe(SCH.context?.authentication)) {
            // have cookie but the page is guarded with IS_AUTHENTICATED_FULLY
            redirect action: 'full', params: params
        }
    }

    /**
     * Login page for users with a remember-me cookie but accessing a IS_AUTHENTICATED_FULLY page.
     */
    def full() {
        def config = SpringSecurityUtils.securityConfig
        render view: 'auth', params: params,
                model: [hasCookie: authenticationTrustResolver.isRememberMe(SCH.context?.authentication),
                        postUrl  : "${request.contextPath}${config.apf.filterProcessesUrl}"]
    }

    /**
     * Callback after a failed login. Redirects to the auth page with a warning message.
     */
    def authfail() {

        String msg = ''
        def exception = session[WebAttributes.AUTHENTICATION_EXCEPTION]
        if (exception) {
            if (exception instanceof AccountExpiredException) {
                msg = g.message(code: "springSecurity.errors.login.expired")
            } else if (exception instanceof CredentialsExpiredException) {
                msg = g.message(code: "springSecurity.errors.login.passwordExpired")
            } else if (exception instanceof DisabledException) {
                msg = g.message(code: "springSecurity.errors.login.disabled")
            } else if (exception instanceof LockedException) {
                msg = g.message(code: "springSecurity.errors.login.locked")
            } else {
                msg = g.message(code: "springSecurity.errors.login.fail")
            }
        }

        if (springSecurityService.isAjax(request)) {
            render([error: msg] as JSON)
        } else {
            flash.message = msg
            redirect action: 'auth', params: params
        }
    }

    /**
     * The Ajax success redirect url.
     */
    def ajaxSuccess() {
        render([success: true, username: springSecurityService.authentication.name] as JSON)
    }

    /**
     * The Ajax denied redirect url.
     */
    def ajaxDenied() {
        render([error: 'access denied'] as JSON)
    }
}

grails-app/views/login/auth.gsp
<style>

body {
    background: #e9e9e9;
    color: #666666;
    font-family: 'RobotoDraft', 'Roboto', sans-serif;
    font-size: 14px;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

/* Pen Title */
.pen-title {
    padding: 50px 0;
    text-align: center;
    letter-spacing: 2px;
}
.pen-title h1 {
    margin: 0 0 20px;
    font-size: 48px;
    font-weight: 300;
}
.pen-title span {
    font-size: 12px;
}
.pen-title span .fa {
    color: #ed2553;
}
.pen-title span a {
    color: #ed2553;
    font-weight: 600;
    text-decoration: none;
}

/* Rerun */
.rerun {
    margin: 0 0 30px;
    text-align: center;
}
.rerun a {
    cursor: pointer;
    display: inline-block;
    background: #ed2553;
    border-radius: 3px;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
    padding: 10px 20px;
    color: #ffffff;
    text-decoration: none;
    -webkit-transition: 0.3s ease;
    transition: 0.3s ease;
}
.rerun a:hover {
    box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
}

/* Scroll To Bottom */
#codepen, #portfolio {
    position: fixed;
    bottom: 30px;
    right: 30px;
    background: #363636;
    width: 56px;
    height: 56px;
    border-radius: 100%;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
    -webkit-transition: 0.3s ease;
    transition: 0.3s ease;
    color: #ffffff;
    text-align: center;
}
#codepen i, #portfolio i {
    line-height: 56px;
}
#codepen:hover, #portfolio:hover {
    box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
}

/* CodePen */
#portfolio {
    bottom: 96px;
    right: 36px;
    background: #ed2553;
    width: 44px;
    height: 44px;
    -webkit-animation: buttonFadeInUp 1s ease;
    animation: buttonFadeInUp 1s ease;
}
#portfolio i {
    line-height: 44px;
}

/* Container */
.container {
    position: relative;
    max-width: 460px;
    width: 100%;
    margin: 0 auto 100px;
}
.container.active .card:first-child {
    background: #f2f2f2;
    margin: 0 15px;
}
.container.active .card:nth-child(2) {
    background: #fafafa;
    margin: 0 10px;
}
.container.active .card.alt {
    top: 20px;
    right: 0;
    width: 100%;
    min-width: 100%;
    height: auto;
    border-radius: 5px;
    padding: 60px 0 40px;
    overflow: hidden;
}
.container.active .card.alt .toggle {
    position: absolute;
    top: 40px;
    right: -70px;
    box-shadow: none;
    -webkit-transform: scale(10);
    transform: scale(10);
    -webkit-transition: -webkit-transform .3s ease;
    transition: -webkit-transform .3s ease;
    transition: transform .3s ease;
    transition: transform .3s ease, -webkit-transform .3s ease;
    font-size: 0;
}
.container.active .card.alt .toggle:before {
    content: '';
}
.container.active .card.alt .title,
.container.active .card.alt .input-container,
.container.active .card.alt .button-container {
    left: 0;
    opacity: 1;
    visibility: visible;
    -webkit-transition: .3s ease;
    transition: .3s ease;
}
.container.active .card.alt .title {
    -webkit-transition-delay: .3s;
    transition-delay: .3s;
}
.container.active .card.alt .input-container {
    -webkit-transition-delay: .4s;
    transition-delay: .4s;
}
.container.active .card.alt .input-container:nth-child(2) {
    -webkit-transition-delay: .5s;
    transition-delay: .5s;
}
.container.active .card.alt .input-container:nth-child(3) {
    -webkit-transition-delay: .6s;
    transition-delay: .6s;
}
.container.active .card.alt .button-container {
    -webkit-transition-delay: .7s;
    transition-delay: .7s;
}

/* Card */
.card {
    position: relative;
    background: #ffffff;
    border-radius: 5px;
    padding: 60px 0 40px 0;
    box-sizing: border-box;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
    -webkit-transition: .3s ease;
    transition: .3s ease;
    /* Title */
    /* Inputs */
    /* Button */
    /* Footer */
    /* Alt Card */
}
.card:first-child {
    background: #fafafa;
    height: 10px;
    border-radius: 5px 5px 0 0;
    margin: 0 10px;
    padding: 0;
}
.card .title {
    position: relative;
    z-index: 1;
    border-left: 5px solid #ed2553;
    margin: 0 0 35px;
    padding: 10px 0 10px 50px;
    color: #ed2553;
    font-size: 32px;
    font-weight: 600;
    text-transform: uppercase;
}
.card .input-container {
    position: relative;
    margin: 0 60px 50px;
}
.card .input-container input {
    outline: none;
    z-index: 1;
    position: relative;
    background: none;
    width: 100%;
    height: 60px;
    border: 0;
    color: #212121;
    font-size: 24px;
    font-weight: 400;
}
.card .input-container input:focus ~ label {
    color: #9d9d9d;
    -webkit-transform: translate(-12%, -50%) scale(0.75);
    transform: translate(-12%, -50%) scale(0.75);
}
.card .input-container input:focus ~ .bar:before, .card .input-container input:focus ~ .bar:after {
    width: 50%;
}
.card .input-container input:valid ~ label {
    color: #9d9d9d;
    -webkit-transform: translate(-12%, -50%) scale(0.75);
    transform: translate(-12%, -50%) scale(0.75);
}
.card .input-container label {
    position: absolute;
    top: 0;
    left: 0;
    color: #757575;
    font-size: 24px;
    font-weight: 300;
    line-height: 60px;
    -webkit-transition: 0.2s ease;
    transition: 0.2s ease;
}
.card .input-container .bar {
    position: absolute;
    left: 0;
    bottom: 0;
    background: #757575;
    width: 100%;
    height: 1px;
}
.card .input-container .bar:before, .card .input-container .bar:after {
    content: '';
    position: absolute;
    background: #ed2553;
    width: 0;
    height: 2px;
    -webkit-transition: .2s ease;
    transition: .2s ease;
}
.card .input-container .bar:before {
    left: 50%;
}
.card .input-container .bar:after {
    right: 50%;
}
.card .button-container {
    margin: 0 60px;
    text-align: center;
}
.card .button-container button {
    outline: 0;
    cursor: pointer;
    position: relative;
    display: inline-block;
    background: 0;
    width: 240px;
    border: 2px solid #e3e3e3;
    padding: 20px 0;
    font-size: 24px;
    font-weight: 600;
    line-height: 1;
    text-transform: uppercase;
    overflow: hidden;
    -webkit-transition: .3s ease;
    transition: .3s ease;
}
.card .button-container button span {
    position: relative;
    z-index: 1;
    color: #ddd;
    -webkit-transition: .3s ease;
    transition: .3s ease;
}
.card .button-container button:before {
    content: '';
    position: absolute;
    top: 50%;
    left: 50%;
    display: block;
    background: #ed2553;
    width: 30px;
    height: 30px;
    border-radius: 100%;
    margin: -15px 0 0 -15px;
    opacity: 0;
    -webkit-transition: .3s ease;
    transition: .3s ease;
}
.card .button-container button:hover, .card .button-container button:active, .card .button-container button:focus {
    border-color: #ed2553;
}
.card .button-container button:hover span, .card .button-container button:active span, .card .button-container button:focus span {
    color: #ed2553;
}
.card .button-container button:active span, .card .button-container button:focus span {
    color: #ffffff;
}
.card .button-container button:active:before, .card .button-container button:focus:before {
    opacity: 1;
    -webkit-transform: scale(10);
    transform: scale(10);
}
.card .footer {
    margin: 40px 0 0;
    color: #d3d3d3;
    font-size: 24px;
    font-weight: 300;
    text-align: center;
}
.card .footer a {
    color: inherit;
    text-decoration: none;
    -webkit-transition: .3s ease;
    transition: .3s ease;
}
.card .footer a:hover {
    color: #bababa;
}
.card.alt {
    position: absolute;
    top: 40px;
    right: -70px;
    z-index: 10;
    width: 140px;
    height: 140px;
    background: none;
    border-radius: 100%;
    box-shadow: none;
    padding: 0;
    -webkit-transition: .3s ease;
    transition: .3s ease;
    /* Toggle */
    /* Title */
    /* Input */
    /* Button */
}
.card.alt .toggle {
    position: relative;
    background: #ed2553;
    width: 140px;
    height: 140px;
    border-radius: 100%;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
    color: #ffffff;
    font-size: 28px;
    line-height: 140px;
    text-align: center;
    cursor: pointer;
}

.card.alt .title,
.card.alt .input-container,
.card.alt .button-container {
    left: 100px;
    opacity: 0;
    visibility: hidden;
}
.card.alt .title {
    position: relative;
    border-color: #ffffff;
    color: #ffffff;
}
.card.alt .title .close {
    cursor: pointer;
    position: absolute;
    top: 0;
    right: 60px;
    display: inline;
    color: #ffffff;
    font-size: 58px;
    font-weight: 400;
}
.card.alt .title .close:before {
    content: '\00d7';
}
.card.alt .input-container input {
    color: #ffffff;
}
.card.alt .input-container input:focus ~ label {
    color: #ffffff;
}
.card.alt .input-container input:focus ~ .bar:before, .card.alt .input-container input:focus ~ .bar:after {
    background: #ffffff;
}
.card.alt .input-container input:valid ~ label {
    color: #ffffff;
}
.card.alt .input-container label {
    color: rgba(255, 255, 255, 0.8);
}
.card.alt .input-container .bar {
    background: rgba(255, 255, 255, 0.8);
}
.card.alt .button-container button {
    width: 100%;
    background: #ffffff;
    border-color: #ffffff;
}
.card.alt .button-container button span {
    color: #ed2553;
}
.card.alt .button-container button:hover {
    background: rgba(255, 255, 255, 0.9);
}
.card.alt .button-container button:active:before, .card.alt .button-container button:focus:before {
    display: none;
}

/* Keyframes */
@-webkit-keyframes buttonFadeInUp {
    0% {
        bottom: 30px;
        opacity: 0;
    }
}
@keyframes buttonFadeInUp {
    0% {
        bottom: 30px;
        opacity: 0;
    }
}

</style>


<div class="pen-title">
    <h1><div class='fheader'><g:message code="springSecurity.login.header"/></div>

        <g:fieldError bean="${bean}" field="password"/>

        <g:if test="${flash.message}">
            <div class="message" style="display: block">${flash.message}</div>
        </g:if>
    </h1>
</div>
<div class="container">
    <div class="card"></div>
    <div class="card">
        <h1 class="title">Login</h1>
        <form action='${postUrl}' method='POST' id='loginForm' class='cssform' autocomplete='off'>
            %{--<form name="loginForm" controller="loginPage" action="loginValidate" method="post">--}%
            <div class="input-container">
                <input type="text" class='text_' name='j_username' id='username'/>
                <label for="Username">Username</label>
                <div class="bar"></div>
            </div>
            <div class="input-container">
                <input type="password" class='text_' name='j_password' id='password'/>
                <label for="Password">Password</label>
                <div class="bar"></div>
            </div>
            <div class="button-container">
                <button><span>Go</span></button>
            </div>
            <div class="footer"><a href="#">Forgot your password?</a></div>
        </form>
    </div>
    <div class="card alt">
        <div class="toggle">
            Sign up
        </div>
        <h1 class="title">Register
            <div class="close"></div>
        </h1>
        <g:form name="myForm" controller="login" action="saveSignUpData" method="post">
            <div class="input-container">
                <input type="text" name="name"  id="signUpUsername" required="required"/>
                <label for="Username">Username</label>
                <div class="bar"></div>
            </div>
            <div class="input-container">
                <input type="password" name="password"  id="signUpPassword" required="required"/>
                <label for="Password">Password</label>
                <div class="bar"></div>
            </div>
            <div class="input-container">
                <input type="password" name="repeatpassword"  id="Repeat Password" required="required"/>
                <label for="Repeat Password">Repeat Password</label>
                <div class="bar"></div>
            </div>
            <div class="button-container">
                <button><span>Sign Up</span></button>
            </div>
        </g:form>
    </div>
</div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

<script>

    $('.toggle').on('click', function() {
        $('.container').stop().addClass('active');
    });

    $('.close').on('click', function() {
        $('.container').stop().removeClass('active');
    });
</script>

grails-app/views/login/dashboard.gsp
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="layout" content="main"/>
    <title>Dashboard</title>
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="page-header">Dashboard</h1>
        </div>
    </div><!--/.row-->

    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-blue panel-widget ">
                <div class="row no-padding">
                    <div class="col-sm-3 col-lg-5 widget-left">
                        <svg class="glyph stroked bag"><use xlink:href="#stroked-bag"></use></svg>
                    </div>
                    <div class="col-sm-9 col-lg-7 widget-right">
                        <div class="large">3</div>
                        <div class="text-muted">Total Events</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-orange panel-widget">
                <div class="row no-padding">
                    <div class="col-sm-3 col-lg-5 widget-left">
                        <svg class="glyph stroked empty-message"><use xlink:href="#stroked-empty-message"></use></svg>
                    </div>
                    <div class="col-sm-9 col-lg-7 widget-right">
                        <div class="large">${eventSize}</div>
                        <div class="text-muted">${eventType} recur</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-teal panel-widget">
                <div class="row no-padding">
                    <div class="col-sm-3 col-lg-5 widget-left">
                        <svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg>
                    </div>
                    <div class="col-sm-9 col-lg-7 widget-right">
                        <div class="large">${totalUser}</div>
                        <div class="text-muted">Total Users</div>
                    </div>
                </div>
            </div>
        </div>

    </div><!--/.row-->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script>
        $( function() {
            $( "#datepicker" ).datepicker();
            $( "#datepickeTo" ).datepicker();

        } );
        $(".datepicker").click(function(){
            $( ".datepicker").hide()
        })
    </script>

    <div class="row">
        <g:form controller="mixPanel" action="fetchRecord"  name="fetchEvents" method="post"     >
            <div class="col-md-3">
                <p>From: <input type="text" id="datepicker" name="fromDate" required="required" placeholder="Date"></p></div>
            <div class="col-md-3"><p>To : <input type="text" id="datepickeTo" name="toDate" required="required" placeholder="Date"></p></div>
            <div class="col-md-3">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-cubes"></i></span>
                    <select name="event" class="form-control" id="accountType" required="required">
                        <option value="">Select Event</option>
                        <option value="page event">Page View</option>
                        <option value="button event">Button Click</option>
                        <option value="link event">Link Click</option>
                    </select>
                </div>
            </div>
            <div class="col-md-3">
                <input type="submit" class="btn btn-primary btn-block" value="Submit"/>    </div>
        </g:form>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Event Details</h2>
            <table class="table">
                <thead>
                <tr>
                    <th>Event Type</th>
                    <th>Event Id</th>
                    <th>User Id</th>
                    <th>User Firstname</th>
                    <th>User Lastname</th>
                    <th>User Email</th>
                </tr>
                </thead>
                <tbody>
                <g:each in="${eventList}" var="dataList" status="i">
                    <tr>
                        <td>${dataList?.eventType}</td>
                        <td>${dataList?.eventId}</td>
                        <td>${dataList?.userId}</td>
                        <td>${dataList?.firstName}</td>
                        <td>${dataList?.lastName}</td>
                        <td>${dataList?.userEmailId}</td>
                    </tr>
                </g:each>

                </tbody>
            </table>

        </div>
    </div><!--/.row-->

    <div class="row">
        <div class="col-md-12">
            <h2>User Details</h2>
            <table class="table">
                <thead>
                <tr>
                    <th>id</th>
                    <th>Firstname</th>
                    <th>Lastname</th>
                    <th>Email</th>
                    <th>Last Seen</th>
                </tr>
                </thead>
                <tbody>
                <g:each in="${userList}" var="data" status="i">
                    <tr class="success">
                        <td>${data.$distinct_id}</td>
                        <td>${data.$properties.$first_name}</td>
                        <td>${data.$properties.$last_name}</td>
                        <td>${data.$properties.$email}</td>
                        <td>${data.$properties.$last_seen}</td>
                    </tr>
                </g:each>

                </tbody>
            </table>
        </div>
    </div><!--/.row-->
</div>

</body>
</html>